name: "mysql-8.0"

services:

  mysql-1:
    image: "docker.io/mysql:8.0"
    platform: "linux/amd64"
    network_mode: "host"
    command:
      - --server-id=1
      - --port=3306
      - --binlog-transaction-dependency-tracking=WRITESET
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  mysql-2:
    image: "docker.io/mysql:8.0"
    platform: "linux/amd64"
    network_mode: "host"
    command:
      - --server-id=2
      - --port=3307
      - --binlog-transaction-dependency-tracking=WRITESET
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  mysql-3:
    image: "docker.io/mysql:8.0"
    platform: "linux/amd64"
    network_mode: "host"
    command:
      - --server-id=3
      - --port=3308
      - --binlog-transaction-dependency-tracking=WRITESET
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
