# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Install binaries"
        run: |
          sudo apt update
          sudo apt install mysql-shell
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: "Install poetry & tox"
        run: |
          pipx install poetry
          pipx install tox
      - name: "Run linters"
        run: tox run -e lint

  test-unit:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Install binaries"
        run: |
          sudo apt update
          sudo apt install mysql-shell
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: "Install poetry & tox"
        run: |
          pipx install poetry
          pipx install tox
      - name: "Run tests"
        run: tox run -e unit
      - name: "Upload Coverage to Codecov"
        uses: codecov/codecov-action@v5

  test-integration:
    name: "Run integration tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # List of supported versions by MySQL Shell
          # https://www.mysql.com/support/supportedplatforms/compatibility.html
          - server: { version: "8.0" }
            shell:  { version: "8.0.45+dfsg-0ubuntu0.24.04.1~ppa1", archive: "data-platform/mysql-shell-8.0" }
          - server: { version: "8.0" }
            shell:  { version: "8.4.8+dfsg-0ubuntu0.24.04.1~ppa1", archive: "data-platform/mysql-shell-8.4" }
          - server: { version: "8.4" }
            shell:  { version: "8.4.8+dfsg-0ubuntu0.24.04.1~ppa1", archive: "data-platform/mysql-shell-8.4" }
    env:
      MYSQL_DATABASE: test
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root_pass
      MYSQL_SHELL_PATH: mysqlsh
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Set up Compose"
        uses: docker/setup-compose-action@v2
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: "Install binaries"
        run: |
          sudo add-apt-repository ppa:${{ matrix.shell.archive }}
          sudo apt update
          sudo apt install mysql-shell=${{ matrix.shell.version }}
      - name: "Install poetry & tox"
        run: |
          pipx install poetry
          pipx install tox
      - name: "Start services"
        run: docker compose -f compose/mysql-${{ matrix.server.version }}.yaml up --wait
      - name: "Run tests"
        run: tox run -e integration
      - name: "Stop services"
        run: docker compose -f compose/mysql-${{ matrix.server.version }}.yaml down
      - name: "Upload Coverage to Codecov"
        uses: codecov/codecov-action@v5
